package br.edu.faculdadeidez.afundeumpolitico;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;

public class Banco {

	public static void main(String[] args) throws Exception {		
		Class.forName( "org.h2.Driver" );		
		
		Connection c = DriverManager.getConnection( 
				"jdbc:h2:pessoas_idez", "root", "root" );
		Statement s = c.createStatement();
		s.execute( "create table pessoas ( id bigint generated by default as identity, primary key (id), nome VARCHAR(255), email VARCHAR(255), endereco VARCHAR(255))" );		
		
		PreparedStatement preparedStatement = c.prepareStatement( 
				"INSERT INTO politicos (nome, linha coluna) VALUES (?, ?, ?)" );
		
		preparedStatement.setString( 1, "José");
		preparedStatement.setInt( 2, 2);
		preparedStatement.setInt( 3 , 7);
		
		preparedStatement.executeUpdate();
		
		c.close();
		
	}
	
}
